name: 'Next Version'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GIT_AUTHOR_NAME: samydoesit
  GIT_AUTHOR_EMAIL: sxburk@gmail.com
  GIT_COMMITTER_NAME: samydoesit
  GIT_COMMITTER_EMAIL: sxburk@gmail.com

on:
  push:
    branches:
      - main
      - beta

jobs:
  next-version:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18 ]

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: 📦 Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"

      - name: 'Starting semantic release'
        run: npm config set workspaces-update false && pnpx multi-semantic-release
